# Site settings
title: Alan Rynne
description: Welcome to my personal webpage!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alanrynne.github.io" # the base hostname & protocol for your site

# User settings
username: Alan Rynne
user_description: a Building Engineer specialized in Parametric Architecture & Computational Design. I am also a self-taught programmer & web-designer, and an overall tech geek!
user_title: 
  - Building Engineer
  - Computational Designer
  - Parametric Specialist
  - BIM Enthusiast
  - Web Designer
  - Tech Geek
email: alan@rynne.es
github_username:  AlanRynne

# Build settings
markdown: Pandoc
highlighter: rouge
permalink: /blog/:title/

destination: ./docs
# Build settings
plugins:
  - jekyll-feed
  - jekyll-pandoc
  - octopress-paginate

pagination:
  limit: false
  per_page: 2
  title_suffix: " (page :num)"
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - from: markdown+implicit_figures+superscript+subscript+table_captions+definition_lists
    #- csl: _styles/apa.csl
    #- bibliography: bibliography/references.bib

paginate_path: "/blog/page:num/"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


collections:
  pages:
    output: true
    permalink: /:path:output_ext
  projects:
    output: true
    permalink: /projects/:name


# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog
  - title: Series
    url: /series
  - title: Download my CV
    url: /assets/docs/AlanRynneCV(Eng).pdf
    external: true

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Skills for main page
skills:
  - title: Architecture Design
    img: "assets/img/triangular-gridshell-outside-Andres-Flajszer.jpg"
    img-author: Andrés Flajszer
    img-author-link: http://www.andresflajszer.com
    description: "With a special interest in freeform architecture, lightweight designs, hybrid structures and the use innovative materials and processes in general."
  - title: "Building Engineering"
    img: "assets/gif/Tensegrity-Generation.gif"
    description: "From more classical MEP, structural and cost control topics, to freeform paneling solutions & complex shape/structural optimizations."
  - title: "Programming"
    img: "assets/img/programming.png"
    description: "I started learning programming on my own a couple years back. Today, I've completed several websites for clients, developed some plugins for Grasshopper and many more cool stuff that you can find in my blog!"
  - title: "Parametric Tools & BIM"
    img: "assets/gif/PHexRotation.gif"
    description: "BIM user & enthusiast since 2011 with a Master's degree in Parametric Design in Architecture since 2018."


hobbies:
  - title: "Technology"
    img: "assets/img/shapeoko.jpg"
    description: "I've built my own 3D printer, CNC, drone...if it's technology related, count me in!"
  - title: "Cooking"
    img: "assets/img/food.png"
    description: "I'm always making stuff, and eating is no exception!"
  - title: "My dog!"
    img: "assets/img/dordo.png"
    description: <i class="fas fa-heart fa-6x" style="color:red;opacity:0.5"></i>
  - title: "Writting"
    img: "assets/img/leeFerrel.jpg"
    description: "I recently grew an interest in writting, so I started my own blog where I write about Architectural Geometry and other stuff..."
  
social:
  - name: LinkedIn
    url: http://www.linkedin.com/alanrynnevidal
    icon: fab fa-linkedin-in
  - name: Instagram
    url: http://www.instagram.com/alanrynne
    icon: fab fa-instagram
  - name: Github
    url: http://www.github.com/AlanRynne
    icon: fab fa-github
  - name: Email
    url: mailto:alan@rynne.es
    icon: far fa-envelope

