name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Google Cloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        
      - uses: google-github-actions/auth@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT }}'
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT }}'
