name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Save artifact
        uses: actions/upload-artifact
        with:
          name: build-artifact
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Google Cloud
    steps:
      - name: Download artifact
        uses: actions/download-artifact
        with:
          name: build-artifact
          path: ./dist
      - uses: google-github-actions/auth
        with:
          project_id: '${{ secrets.GCP_PROJECT }}'
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine
        with:
          project_id: '${{ secrets.GCP_PROJECT }}'
